version: '3.8'

services:
  backend:
    image: webbylabhub/movies
    container_name: movies-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: antiokh1/movies
    container_name: movies-frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped
